default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  database: <%= ENV.fetch("DATABASE_NAME", File.basename(Rails.root)) %>_dev
  <<: *default

test:
  database: <%= ENV.fetch("DATABASE_NAME", File.basename(Rails.root)) %>_test
  <<: *default

production:
  <<: *default
